# Generated by Django 4.2.1 on 2023-05-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatsession_chatentry_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatentry',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
