# Generated by Django 4.2.1 on 2023-05-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatsession1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatsession'),
        ),
        migrations.CreateModel(
            name='ChatEntry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('reply', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.chatsession')),
            ],
        ),
    ]
