# Generated by Django 4.2.1 on 2023-05-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatentry_chat_session_chatentry1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatentry1',
            name='chat_session',
        ),
        migrations.DeleteModel(
            name='ChatSession1',
        ),
        migrations.AlterField(
            model_name='chatentry',
            name='chat_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.chatsession'),
        ),
        migrations.DeleteModel(
            name='ChatEntry1',
        ),
    ]
