# Generated by Django 4.2.1 on 2023-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_chatentry1_chat_session_delete_chatsession1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatentry',
            name='chat_session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
